# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etransfer.proto\x12\x08transfer\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\")\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x0b\n\x03seq\x18\x02 \x01(\x05\"-\n\x0eUploadResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x7f\n\x08Transfer\x12\x38\n\x08\x44ownload\x12\x15.transfer.FileRequest\x1a\x13.transfer.FileChunk0\x01\x12\x39\n\x06Upload\x12\x13.transfer.FileChunk\x1a\x18.transfer.UploadResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEREQUEST']._serialized_start=28
  _globals['_FILEREQUEST']._serialized_end=59
  _globals['_FILECHUNK']._serialized_start=61
  _globals['_FILECHUNK']._serialized_end=102
  _globals['_UPLOADRESPONSE']._serialized_start=104
  _globals['_UPLOADRESPONSE']._serialized_end=149
  _globals['_TRANSFER']._serialized_start=151
  _globals['_TRANSFER']._serialized_end=278
# @@protoc_insertion_point(module_scope)
